stages:
- name: Build
  steps:
  - runScriptConfig:
      image: loongson.harbor.cn/loongnix/maven:3-openjdk-8
      shellScript: |-
        mvn clean install
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: loongnix/example-greenhouse:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: loongson.harbor.cn
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_PASSWORD: admin
      PLUGIN_REGISTRY: loongson.harbor.cn
      PLUGIN_USERNAME: admin
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
